name: deploy on prod
'on' :
  push:
    branches:
      - prod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkoutout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-lab13-frontend:latest
      -
        name: composing
        run: |
          mkdir se331-lab13-frontend
          cp docker-compose.yml se331-lab13-frontend/docker-compose.yml
          cd se331-lab13-frontend
          docker-compose -H ${{ secrets.HOST_SERVER }} pull
          docker-compose -H ${{ secrets.HOST_SERVER }} up -d 